# Generated by Django 3.2.18 on 2023-03-27 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projects",
            old_name="author_user_id",
            new_name="author_user",
        ),
    ]
