# Generated by Django 3.2.18 on 2023-04-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributors",
            name="role",
            field=models.CharField(default="contributeur", max_length=20, null=True),
        ),
    ]
