# Generated by Django 3.2.18 on 2023-03-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_users_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="comment",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="projects",
            name="project",
            field=models.PositiveIntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="user",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
