# Generated by Django 3.2.18 on 2023-03-14 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_auto_20230314_2121"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="comment",
            new_name="comment_id",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="user",
            new_name="user_id",
        ),
    ]
