# Generated by Django 3.2.18 on 2023-03-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_auto_20230314_2122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="user_id",
            field=models.PositiveIntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
