# Generated by Django 3.2.18 on 2023-03-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_users_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
