# Generated by Django 3.2.18 on 2023-03-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_users_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="permissions",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="users",
            name="user_id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
