# Generated by Django 3.2.18 on 2023-03-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("api", "0007_auto_20230315_1006"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="permissions",
        ),
        migrations.AddField(
            model_name="users",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                related_query_name="users",
                to="auth.Permission",
                verbose_name="user permissions",
            ),
        ),
    ]
